### ISSUE TITLE
Mac version

### ISSUE THREAD

**Issue by kumicat** [adnv3k/GestureSesh#12]
Hi, I love this program so much. The features are extremely useful and I really enjoy using it for my figure studies. I'm wondering if there is a version available for Mac? I'd like to download this on my Macbook laptop as well. I'm a little new to github, so I'm sorry if this is a stupid question. 
Thank you!

**Comment by adnv3k** [comment]
Hi @kumicat! 

So happy that you enjoy using it and thanks for reaching out! No, it's totally cool. Not a stupid question at all. Unfortunately, there is not an accessible Mac version available from me. There *is* a way to run it, but that would be a little bit more involved (getting the source files from here to your Mac, then running it with Python). There aren't solid plans to continue development for GestureSesh any time soon, but I may add a guide to running it on a Mac soon.

Thank you so much!
Kind regards,
Ali

**Comment by kumicat** [comment]
Hi Ali,
Thank you so much! That would be great, I'd gladly try running it with Python once you add a guide. 
Have a great day!

**Comment by adnv3k** [comment]
Hi @kumicat! Just added macOS support. Hope it helps!
